[git_status]
modified = '!${count}(green)'
deleted = '✘${count}'
staged = '+${count}(green)'
ahead = '⇡${count}'
behind = '⇣${count}'
renamed = '»${count}'
stashed = '\$${count}'
diverged = '⇕⇡${ahead_count}⇣${behind_count}'
