[git_status]
modified = '[!${count}](bold yellow)'
deleted = '[✘${count}](bold red)'
staged = '[+${count}(green)](bold green)'
ahead = '⇡${count}'
behind = '⇣${count}'
renamed = '»${count}'
stashed = '\$${count}'
diverged = '⇕⇡${ahead_count}⇣${behind_count}'
