"$schema" = 'https://starship.rs/config-schema.json'

[git_status]
modified = '[!${count}](bold yellow)'
deleted = '[✘${count}](bold red)'
staged = '[+${count}(green)](bold green)'
ahead = '⇡${count}'
behind = '⇣${count}'
renamed = '»${count}'
stashed = '*${count}'
untracked = '[?${count}](bold blue)'
diverged = '⇡${ahead_count}⇣${behind_count}'
conflicted = "≠${count}"

[shell]
disabled = false

[line_break]
disabled = true

[rust]
disabled = true

[swift]
disabled = true

[conda]
format = 'via [$symbol]($style) '

[aws]
disabled = true
